name: 'apis/poi/ tests'

on:
  push:
    paths:
    - 'apis/poi/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'apis/poi/**'
  workflow_dispatch:

jobs:
  dotnet-poi-test:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'apis/poi/'

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --filter "FullyQualifiedName~UnitTest" --logger "trx;LogFileName=UnitTestResults.trx" --results-directory ./TestResults
