name: 'apis/poi/ tests'

on:
  push:
    paths:
    - 'apis/poi/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'apis/poi/**'
  workflow_dispatch:

jobs:
  dotnet-poi-test:
    name: 'apis/poi/ tests'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'apis/poi/'

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      id: setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
  
    - name: Restore dependencies
      id: dependencies
      run: dotnet restore

    - name: Build
      id: build
      run: dotnet build --no-restore

    - name: Test
      id: test
      run: dotnet test --no-build --filter "FullyQualifiedName~UnitTest" --logger "trx;LogFileName=UnitTestResults.trx" --results-directory ./TestResults

    - name: CreateIssue
      if: ${{ failure() }}
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/DevOpsOpenHack/devopsohzuehlke2/issues \
        -d '{"title": "${{ github.workflow }} has failed: ${{ github.run_id }}",
        "body": "Failure in run: _${{ github.run_id }}_."
        }'

    - name: Comment PR
      uses: allthatjazzleo/actions-pull-request-add-comment@master
      if: github.event_name == 'pull_request' && failure()
      with:
        message: "### Unit Test `failure`
<details>
<summary>Workflow details</summary>

Workflow name: `${{ github.workflow }}`
Action: `${{ github.event_name }}`
Job: `${{ github.job }}`
PR: #${{ github.event.number }}
</details>

Test details: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
Pusher: @${{ github.actor }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
