name: 'Userprofile API CI/CD Pipeline: build/test/deploy'

on:
  push:
    paths:
    - 'apis/userprofile/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'apis/userprofile/**'
  workflow_dispatch:
    inputs:
      force-deployment:
        type: boolean
        description: Force the deployment step

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'apis/userprofile/'

    steps:

    - name: build 
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
      run: npm ci
      run: npm build
      run: npm test

    - name: test 
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
      run: npm test
