name: 'Userprofile API CI/CD Pipeline: build/test/deploy'

on:
  push:
    paths:
    - '.github/workflows/userprofile.yml'
    - 'apis/userprofile/**'
    branches: [ feature/userprofile-cicd ]
  pull_request:
    paths:
    - 'apis/userprofile/**'
  workflow_dispatch:
    inputs:
      force-deployment:
        type: boolean
        description: Force the deployment step

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'apis/userprofile/'

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v2
      with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

    - name: Build
      id: build
      run: |
        npm ci
        npm build

    - name: Test
      id: test
      run: npm test
      
    - name: Set build version
      id: build-version
      run: echo "::set-output name=tag::$(date +%s)-${{ github.sha }}"
      
    - name: Build and push the docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u devopscamp2022 --password-stdin
        docker build --tag ghcr.io/devopscamp2022/api-userprofile:${{ steps.build-version.outputs.tag }} --build-arg build_version=${{ steps.build-version.outputs.tag }} --file Dockerfile .
        docker push ghcr.io/devopscamp2022/api-userprofile:${{ steps.build-version.outputs.tag }}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
